server:
  port: 8080

spring:
  application:
    name: aiplane-api-server

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    dev.madmmas.aimanager: DEBUG
